version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
   # ports:
   #  - "5432:5432"

  web:
    image: devtown.filamentcalc 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHostname: db
      PGDB: filamentcalc
      PGUsername: postgres
      PGPassword: example
      SeedDemoData: J
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "9001:80"
    depends_on:
      - "db"