version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
     - "5433:5432"

  web:
    image: devtown.filamentcalc 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHostname: db
      PGDB: filamentcalc
      PGUsername: postgres
      PGPassword: example
      #SeedDemoData: J
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - "db"