version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
   # ports:
     #- "5433:5432"
    networks:
      - internal-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data    # Diese Zeile hinzufügen


    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d filamentcalc" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  web:
    image: devtown.filamentcalc 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGHostname: db
      PGDB: filamentcalc
      PGUsername: postgres
      PGPassword: example
      ASPNETCORE_URLS: http://+:8080
      #SeedDemoData: J
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - internal-network
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge
    internal: false  # ASP.NET App braucht Internet-Zugang für Updates etc.