name: dotnet_test

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: run Nuke-Test
      run: ./build.sh test
    
