name: dotnet_test

on:
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches: 
    - master
    
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
      LANG: de_DE.UTF-8
      LC_ALL: de_DE.UTF-8

    steps:
      - uses: actions/checkout@v2
      - name: Install German locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo update-locale LANG=de_DE.UTF-8
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      - name: run Nuke-Test
        run: ./build.sh test
    
